controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    # =========================
    # 상태 퍼블리셔
    # =========================
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # =========================
    # 바퀴 (diff_drive)
    # =========================
    diff_drive_base_controller:
      ros__parameters:
        publish_rate: 50
        left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint"]
        right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint"]
        wheel_separation: 0.4       # URDF 맞춤
        wheel_radius: 0.035         # URDF 맞춤
        use_stamped_vel: false
        enable_odom_tf: true
        publish_wheel_joint_controller: true

    # =========================
    # 그리퍼 개별 JointPositionController
    # =========================
    left_gripper_joint_controller:
      type: position_controllers/JointPositionController
      joint: left_gripper_joint
      interface_name: position

    right_gripper_joint_controller:
      type: position_controllers/JointPositionController
      joint: right_gripper_joint
      interface_name: position

    gripper_extension_controller:
      type: position_controllers/JointPositionController
      joint: gripper_extension
      interface_name: position

    # =========================
    # 머리 회전
    # =========================
    head_controller:
      type: position_controllers/JointGroupPositionController
      ros__parameters:
        joints:
          - head_swivel
        command_interfaces:
          - position
        state_interfaces:
          - position

